DROP TYPE IF EXISTS skin_type, prod_catgeory, range_type;

CREATE TYPE skin_type AS ENUM (
    'Combination Skin',
    'Oily Skin',
    'Normal Skin',
    'Dry Skin'
);

CREATE TYPE prod_category AS ENUM (
    'Cleanse',
    'Treat',
    'Tone', 
    'Nourish',
    'Hydrate'
);


CREATE TYPE range_type AS ENUM (
    '$$$',
    '$$',
    '$'
);

CREATE TABLE skincare_products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    content TEXT NOT NULL,
    image TEXT NOT NULL,
    url TEXT,
    originalprice FLOAT NOT NULL,
    range range_type,
    skintype skin_type,
    category prod_category,
    rating INTEGER,
    details TEXT
);

